apiVersion: v2
name: batch
description: Batch processing components
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: spark-operator
    version: "*"
    repository: https://kubeflow.github.io/spark-operator
    condition: sparkOperator.enabled
